# Generated by Django 3.2.19 on 2024-06-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('temperatura', models.CharField(max_length=255)),
                ('humedad', models.CharField(max_length=255)),
                ('latitud', models.CharField(max_length=255)),
                ('longitud', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'informacion',
                'managed': False,
            },
        ),
    ]
