# Generated by Django 3.2.19 on 2024-06-21 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacion',
            options={},
        ),
    ]
