# Generated by Django 3.2.19 on 2024-06-21 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nueva_app', '0002_alter_informacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informacion',
            options={'managed': True},
        ),
    ]
